import pytest

from boring_converter.soil import classify


@pytest.mark.parametrize("name,expected", [
    ("砂質シルト", "silt"),
    ("シルト質砂", "sand"),
    ("砂混りシルト", "silt"),
    ("砂礫", "gravel"),
    ("砂利・礫混り砂", "sand"),
    ("砂利", "gravel"),
    ("粘土質シルト", "silt"),
    ("砂質粘性土", "clay"),
    ("盛土(砂質シルト)", "fill"),
    ("砂質盛土", "fill"),
    ("表土(ガラ、粘土混じり砂)", "topsoil"),
    ("砂質泥岩", "rock"),
    ("軟岩・風化岩", "rock"),
    ("ロ－ム", "volcanic"),
    ("火山灰質粘性土", "volcanic"),
    ("火山灰混り砂", "sand"),
    ("高有機質土(腐植土)", "organic"),
    ("有機質シルト", "organic"),
    ("有機質土混り砂", "sand"),
    ("シルト(Ｍ)", "silt"),
    ("細～中砂", "sand"),
    ("表層", "topsoil"),
    ("コンクリ", "fill"),
    ("覆土ブロック", "fill"),
    ("沈泥土", "silt"),
    ("硬質しると", "silt"),
    ("軟泥", "clay"),
    ("黒ボク", "volcanic"),
    ("木片", "unknown"),
    ("チャート", "rock"),
    ("風化チャート", "rock"),
    ("石炭", "rock"),
    ("中硬質シラス", "volcanic"),
    ("しらす", "volcanic"),
    ("黒ぼく", "volcanic"),
    ("火砕流堆積物", "volcanic"),
    ("耕作土", "topsoil"),
    ("捨石", "fill"),
    ("マサ", "sand"),
    ("崖錐堆積物", "unknown"),
    ("チャート礫", "gravel"),
    ("石炭片混じり中粒砂", "sand"),
    ("亜炭混じりシルト", "silt"),
    ("粘土混じり石炭", "rock"),
    ("角礫状破砕帯", "rock"),
    (None, "unknown"),
    ("", "unknown"),
])
def test_classify(name, expected):
    assert classify(name) == expected
